### PR TITLE
Create lindo

### PR DESCRIPTION
**Pull request by dellllll**

### CODE REVIEW

**Comment by tintin10q** [comment]
Sorry for just seeing this now. What exactly are you proposing to add?

**Comment by Cinahcem** [comment]
Hello,
why when i try to download the file, avast detects malware gen ...?

**Comment by tintin10q** [comment]
Chinahcem what file do you mean the main project files or the file from the pull request.

**Comment by Cinahcem** [comment]
The file : minecraft_logs_analizer.zip

**Comment by tintin10q** [comment]
Unfortunately there is a bug with pyinstaller (the program I used to create an .exe from the .py) and this makes these .exe files being flagged as false positive viruses. 
https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg

**Comment by Cinahcem** [comment]
Okay thank you, if I deactivate the anti virus there will be no problem

**Comment by tintin10q** [comment]
No. But if you really don't trust it you can always use the py version.

**Comment by Cinahcem** [comment]
How can I download this version?

**Comment by tintin10q** [comment]
https://github.com/tintin10q/minecraft-logs-analyzer/releases

It is the pyw version.

And follow the "This next part is only for those who use the .pyw version" instructions from the readme.

**Comment by Cinahcem** [comment]
Thanks, it works !

**Comment by tintin10q** [comment]
Great

**Comment by CyberPunk37** [comment]
Hi, I am looking for a tool to analyze the logs of minecraft server.
Just wanna know how many players log-in, how many times the players login? 
how much the playtime of the players?
Which region do the players come from?

Could you help to add these function into your analyzer? or any other tool you can suggest me.
Thanks for your kindly help

**Comment by tintin10q** [comment]
Sorry at the moment I am quite busy with other projects. 

I wouldn't really know what other tools provide this functionality but perhaps there are plugins out there that what you want.

**Pull request closed without merging**
